"""initial_schema

Revision ID: 38b9d44a6ff1
Revises: 
Create Date: 2026-09-27 01:30:58.131616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b9d44a6ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayur_adverse_events_orm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('trial_id', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('adverse_event', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('serious', sa.String(length=10), nullable=True),
    sa.Column('suspected_treatment', sa.String(length=255), nullable=True),
    sa.Column('date_reported', sa.String(length=50), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ayur_adverse_events_orm_event_id'), 'ayur_adverse_events_orm', ['event_id'], unique=True)
    op.create_index(op.f('ix_ayur_adverse_events_orm_id'), 'ayur_adverse_events_orm', ['id'], unique=False)
    op.create_index(op.f('ix_ayur_adverse_events_orm_patient_id'), 'ayur_adverse_events_orm', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ayur_adverse_events_orm_trial_id'), 'ayur_adverse_events_orm', ['trial_id'], unique=False)
    op.create_table('ayur_approvals_orm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=50), nullable=True),
    sa.Column('trial_id', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('approval_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.String(length=50), nullable=True),
    sa.Column('decision_date', sa.String(length=50), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('action_required', sa.String(length=255), nullable=True),
    sa.Column('signature_id', sa.String(length=100), nullable=True),
    sa.Column('signature_hash', sa.String(length=100), nullable=True),
    sa.Column('signed_by', sa.String(length=100), nullable=True),
    sa.Column('signed_at', sa.String(length=50), nullable=True),
    sa.Column('signing_intent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ayur_approvals_orm_approval_id'), 'ayur_approvals_orm', ['approval_id'], unique=True)
    op.create_index(op.f('ix_ayur_approvals_orm_id'), 'ayur_approvals_orm', ['id'], unique=False)
    op.create_index(op.f('ix_ayur_approvals_orm_trial_id'), 'ayur_approvals_orm', ['trial_id'], unique=False)
    op.create_table('ayur_trials_orm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.String(length=50), nullable=False),
    sa.Column('trial_name', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lead_institution', sa.String(length=255), nullable=True),
    sa.Column('target_participants', sa.Integer(), nullable=True),
    sa.Column('enrolled_participants', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('completion_date', sa.String(length=50), nullable=True),
    sa.Column('ctri_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ctri_number')
    )
    op.create_index(op.f('ix_ayur_trials_orm_condition'), 'ayur_trials_orm', ['condition'], unique=False)
    op.create_index(op.f('ix_ayur_trials_orm_id'), 'ayur_trials_orm', ['id'], unique=False)
    op.create_index(op.f('ix_ayur_trials_orm_trial_id'), 'ayur_trials_orm', ['trial_id'], unique=True)
    op.create_table('esignatures_orm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature_id', sa.String(length=100), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('signer_name', sa.String(length=100), nullable=True),
    sa.Column('signer_role', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.String(length=50), nullable=True),
    sa.Column('signature_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_signature_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esignatures_orm_id'), 'esignatures_orm', ['id'], unique=False)
    op.create_index(op.f('ix_esignatures_orm_record_id'), 'esignatures_orm', ['record_id'], unique=False)
    op.create_index(op.f('ix_esignatures_orm_record_type'), 'esignatures_orm', ['record_type'], unique=False)
    op.create_index(op.f('ix_esignatures_orm_signature_id'), 'esignatures_orm', ['signature_id'], unique=True)
    op.drop_table('ctms_milestones')
    op.drop_table('ayur_trials')
    op.drop_index(op.f('ix_visits_trial_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_table('ctms_monitoring_visits')
    op.drop_table('user_sessions')
    op.drop_table('ayur_approvals')
    op.drop_table('pv_reporting_deadlines')
    op.drop_table('ayur_patient_treatments')
    op.drop_index(op.f('ix_protocol_deviations_trial_id'), table_name='protocol_deviations')
    op.drop_table('protocol_deviations')
    op.drop_index(op.f('ix_eligibility_trial_id'), table_name='eligibility')
    op.drop_table('eligibility')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_investigators_affiliation'), table_name='investigators')
    op.drop_index(op.f('ix_investigators_is_aiia'), table_name='investigators')
    op.drop_index(op.f('ix_investigators_name'), table_name='investigators')
    op.drop_table('investigators')
    op.drop_table('ctms_timelines')
    op.drop_table('ayur_patients')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_trial_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_adverse_events_event_term'), table_name='adverse_events')
    op.drop_index(op.f('ix_adverse_events_is_serious'), table_name='adverse_events')
    op.drop_index(op.f('ix_adverse_events_trial_id'), table_name='adverse_events')
    op.drop_table('adverse_events')
    op.drop_index(op.f('ix_compliance_checks_trial_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_table('ayur_safety_signals')
    op.drop_table('ayur_adverse_events')
    op.drop_table('ctms_recruitment')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_trial_investigators_investigator_id'), table_name='trial_investigators')
    op.drop_index(op.f('ix_trial_investigators_trial_id'), table_name='trial_investigators')
    op.drop_table('trial_investigators')
    op.drop_index(op.f('ix_trial_milestones_trial_id'), table_name='trial_milestones')
    op.drop_table('trial_milestones')
    op.drop_index(op.f('ix_trials_ctri_number'), table_name='trials')
    op.drop_index(op.f('ix_trials_is_aiia'), table_name='trials')
    op.drop_index(op.f('ix_trials_is_ayush'), table_name='trials')
    op.drop_index(op.f('ix_trials_phase'), table_name='trials')
    op.drop_index(op.f('ix_trials_post_graduation_thesis'), table_name='trials')
    op.drop_index(op.f('ix_trials_recruitment_status'), table_name='trials')
    op.drop_index(op.f('ix_trials_registered_on'), table_name='trials')
    op.drop_index(op.f('ix_trials_registration_type'), table_name='trials')
    op.drop_index(op.f('ix_trials_type_of_trial'), table_name='trials')
    op.drop_table('trials')
    op.drop_table('ctms_protocol_deviations')
    op.drop_table('pv_safety_signals')
    op.drop_table('esignatures')
    op.drop_index(op.f('ix_safety_reports_trial_id'), table_name='safety_reports')
    op.drop_table('safety_reports')
    op.drop_table('ayur_notifications')
    op.drop_index(op.f('ix_interventions_intervention_name'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_trial_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_table('document_versions')
    op.drop_table('ayur_sites')
    op.drop_table('ayur_gcp_checklist')
    op.drop_table('ayur_audit_trail')
    op.drop_index(op.f('ix_outcomes_outcome_type'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_trial_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_sponsors_name'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_trial_id'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_study_sites_site_name'), table_name='study_sites')
    op.drop_index(op.f('ix_study_sites_trial_id'), table_name='study_sites')
    op.drop_table('study_sites')
    op.drop_index(op.f('ix_enrollment_trial_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_table('hash_audit_chain')
    op.drop_table('ayur_doctors')
    op.drop_index(op.f('ix_cdisc_mappings_codelist_code'), table_name='cdisc_mappings')
    op.drop_index(op.f('ix_cdisc_mappings_concept_code'), table_name='cdisc_mappings')
    op.drop_index(op.f('ix_cdisc_mappings_standard_name'), table_name='cdisc_mappings')
    op.drop_index(op.f('ix_cdisc_mappings_term'), table_name='cdisc_mappings')
    op.drop_table('cdisc_mappings')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('doc_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=True),
    sa.Column('trial_ctri', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('current_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(length=150), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('file_size_kb', sa.INTEGER(), nullable=False),
    sa.Column('checksum_sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('security_classification', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdisc_mappings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('concept_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codelist_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('term', sa.VARCHAR(length=255), nullable=False),
    sa.Column('standard_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=True),
    sa.Column('ctri_field_mapped', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdisc_mappings_term'), 'cdisc_mappings', ['term'], unique=False)
    op.create_index(op.f('ix_cdisc_mappings_standard_name'), 'cdisc_mappings', ['standard_name'], unique=False)
    op.create_index(op.f('ix_cdisc_mappings_concept_code'), 'cdisc_mappings', ['concept_code'], unique=False)
    op.create_index(op.f('ix_cdisc_mappings_codelist_code'), 'cdisc_mappings', ['codelist_code'], unique=False)
    op.create_table('ayur_doctors',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('avatar', sa.TEXT(), nullable=True),
    sa.Column('qualification', sa.TEXT(), nullable=False),
    sa.Column('specialization', sa.TEXT(), nullable=False),
    sa.Column('experience_years', sa.INTEGER(), nullable=False),
    sa.Column('current_site', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_table('hash_audit_chain',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.Column('user_name', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('entity', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.TEXT(), nullable=False),
    sa.Column('previous_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('device_metadata', sa.TEXT(), nullable=True),
    sa.Column('prev_hash', sa.TEXT(), nullable=False),
    sa.Column('current_hash', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('target_enrollment', sa.INTEGER(), nullable=True),
    sa.Column('actual_enrolled', sa.INTEGER(), nullable=True),
    sa.Column('screened', sa.INTEGER(), nullable=True),
    sa.Column('withdrawn', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['study_sites.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_trial_id'), 'enrollment', ['trial_id'], unique=False)
    op.create_table('study_sites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.TEXT(), nullable=False),
    sa.Column('site_address', sa.TEXT(), nullable=True),
    sa.Column('pi_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('num_sites', sa.VARCHAR(length=50), nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sites_trial_id'), 'study_sites', ['trial_id'], unique=False)
    op.create_index(op.f('ix_study_sites_site_name'), 'study_sites', ['site_name'], unique=False)
    op.create_table('sponsors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('sponsor_type', sa.VARCHAR(length=150), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_trial_id'), 'sponsors', ['trial_id'], unique=False)
    op.create_index(op.f('ix_sponsors_name'), 'sponsors', ['name'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('outcome_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('outcome_name', sa.TEXT(), nullable=False),
    sa.Column('timepoints', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_trial_id'), 'outcomes', ['trial_id'], unique=False)
    op.create_index(op.f('ix_outcomes_outcome_type'), 'outcomes', ['outcome_type'], unique=False)
    op.create_table('ayur_audit_trail',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('audit_id', sa.TEXT(), nullable=False),
    sa.Column('user_name', sa.TEXT(), nullable=False),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('module', sa.TEXT(), nullable=False),
    sa.Column('previous_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_table('ayur_gcp_checklist',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('is_completed', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_reviewed', sa.TEXT(), nullable=False),
    sa.Column('reviewed_by', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('ayur_sites',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('site_id', sa.TEXT(), nullable=False),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('hospital_name', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('pi_name', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.TEXT(), nullable=False),
    sa.Column('end_date', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('participants_enrolled', sa.INTEGER(), nullable=False),
    sa.Column('participants_target', sa.INTEGER(), nullable=False),
    sa.Column('progress_pct', sa.INTEGER(), nullable=False),
    sa.Column('doctor_name', sa.TEXT(), nullable=False),
    sa.Column('coordinator_name', sa.TEXT(), nullable=False),
    sa.Column('pending_issues', sa.TEXT(), nullable=True),
    sa.Column('outcome_trend_json', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('file_size_kb', sa.INTEGER(), nullable=False),
    sa.Column('checksum_sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(length=150), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_summary', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('arm_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('intervention_name', sa.TEXT(), nullable=True),
    sa.Column('intervention_details', sa.TEXT(), nullable=True),
    sa.Column('comparator_name', sa.TEXT(), nullable=True),
    sa.Column('comparator_details', sa.TEXT(), nullable=True),
    sa.Column('dosage_form', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_trial_id'), 'interventions', ['trial_id'], unique=False)
    op.create_index(op.f('ix_interventions_intervention_name'), 'interventions', ['intervention_name'], unique=False)
    op.create_table('ayur_notifications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('notification_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('target_route', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_table('safety_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('reporting_period_start', sa.DATE(), nullable=True),
    sa.Column('reporting_period_end', sa.DATE(), nullable=True),
    sa.Column('submission_date', sa.DATE(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_reports_trial_id'), 'safety_reports', ['trial_id'], unique=False)
    op.create_table('esignatures',
    sa.Column('signature_id', sa.TEXT(), nullable=True),
    sa.Column('record_type', sa.TEXT(), nullable=False),
    sa.Column('record_id', sa.TEXT(), nullable=False),
    sa.Column('signer_name', sa.TEXT(), nullable=False),
    sa.Column('signer_role', sa.TEXT(), nullable=False),
    sa.Column('intent', sa.TEXT(), nullable=False),
    sa.Column('signed_at', sa.TEXT(), nullable=False),
    sa.Column('signature_hash', sa.TEXT(), nullable=False),
    sa.Column('previous_signature_hash', sa.TEXT(), nullable=False),
    sa.Column('verification_status', sa.TEXT(), server_default=sa.text("'VALID'"), nullable=True),
    sa.PrimaryKeyConstraint('signature_id')
    )
    op.create_table('pv_safety_signals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('signal_code', sa.TEXT(), nullable=True),
    sa.Column('trial_id', sa.INTEGER(), nullable=True),
    sa.Column('ctri_number', sa.TEXT(), nullable=True),
    sa.Column('trial_title', sa.TEXT(), nullable=True),
    sa.Column('event_term', sa.TEXT(), nullable=True),
    sa.Column('current_frequency', sa.INTEGER(), nullable=True),
    sa.Column('previous_frequency', sa.INTEGER(), nullable=True),
    sa.Column('change_pct', sa.REAL(), nullable=True),
    sa.Column('severity', sa.TEXT(), nullable=True),
    sa.Column('review_status', sa.TEXT(), nullable=True),
    sa.Column('detected_date', sa.TEXT(), nullable=True),
    sa.Column('reviewer', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ctms_protocol_deviations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('deviation_code', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.TEXT(), nullable=False),
    sa.Column('trial_title', sa.TEXT(), nullable=False),
    sa.Column('site_name', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('date_identified', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Open'"), nullable=True),
    sa.Column('resolution', sa.TEXT(), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('public_title', sa.TEXT(), nullable=False),
    sa.Column('scientific_title', sa.TEXT(), nullable=True),
    sa.Column('trial_acronym', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type_of_trial', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type_of_study', sa.VARCHAR(length=150), nullable=True),
    sa.Column('study_design', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('post_graduation_thesis', sa.VARCHAR(length=10), nullable=True),
    sa.Column('recruitment_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('registration_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('registered_on', sa.DATE(), nullable=True),
    sa.Column('last_modified_on', sa.DATE(), nullable=True),
    sa.Column('date_first_enrollment', sa.DATE(), nullable=True),
    sa.Column('date_completion', sa.DATE(), nullable=True),
    sa.Column('target_sample_size', sa.INTEGER(), nullable=True),
    sa.Column('brief_summary', sa.TEXT(), nullable=True),
    sa.Column('dcgi_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_aiia', sa.BOOLEAN(), nullable=True),
    sa.Column('is_ayush', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trials_type_of_trial'), 'trials', ['type_of_trial'], unique=False)
    op.create_index(op.f('ix_trials_registration_type'), 'trials', ['registration_type'], unique=False)
    op.create_index(op.f('ix_trials_registered_on'), 'trials', ['registered_on'], unique=False)
    op.create_index(op.f('ix_trials_recruitment_status'), 'trials', ['recruitment_status'], unique=False)
    op.create_index(op.f('ix_trials_post_graduation_thesis'), 'trials', ['post_graduation_thesis'], unique=False)
    op.create_index(op.f('ix_trials_phase'), 'trials', ['phase'], unique=False)
    op.create_index(op.f('ix_trials_is_ayush'), 'trials', ['is_ayush'], unique=False)
    op.create_index(op.f('ix_trials_is_aiia'), 'trials', ['is_aiia'], unique=False)
    op.create_index(op.f('ix_trials_ctri_number'), 'trials', ['ctri_number'], unique=False)
    op.create_table('trial_milestones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('milestone_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('target_date', sa.DATE(), nullable=True),
    sa.Column('achieved_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_milestones_trial_id'), 'trial_milestones', ['trial_id'], unique=False)
    op.create_table('trial_investigators',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('investigator_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['investigator_id'], ['investigators.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_investigators_trial_id'), 'trial_investigators', ['trial_id'], unique=False)
    op.create_index(op.f('ix_trial_investigators_investigator_id'), 'trial_investigators', ['investigator_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=150), nullable=True),
    sa.Column('changes_json', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('ctms_recruitment',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.TEXT(), nullable=False),
    sa.Column('trial_title', sa.TEXT(), nullable=False),
    sa.Column('target_enrollment', sa.INTEGER(), nullable=False),
    sa.Column('current_enrollment', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('enrollment_pct', sa.REAL(), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('expected_enrollment', sa.INTEGER(), nullable=False),
    sa.Column('enrollment_gap', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_trend_json', sa.TEXT(), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('last_updated', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ayur_adverse_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.TEXT(), nullable=False),
    sa.Column('patient_id', sa.TEXT(), nullable=False),
    sa.Column('patient_name', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('adverse_event', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('serious', sa.TEXT(), server_default=sa.text("'No'"), nullable=False),
    sa.Column('suspected_treatment', sa.TEXT(), nullable=False),
    sa.Column('date_reported', sa.TEXT(), nullable=False),
    sa.Column('action_taken', sa.TEXT(), nullable=True),
    sa.Column('outcome', sa.TEXT(), nullable=True),
    sa.Column('reported_by', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Reported'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('ayur_safety_signals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('signal_id', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('adverse_event_type', sa.TEXT(), nullable=False),
    sa.Column('reported_count', sa.INTEGER(), nullable=False),
    sa.Column('threshold', sa.INTEGER(), nullable=False),
    sa.Column('date_detected', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active Signal'"), nullable=False),
    sa.Column('recommendation', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_table('compliance_checks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('checked_at', sa.DATETIME(), nullable=True),
    sa.Column('checked_by', sa.VARCHAR(length=150), nullable=True),
    sa.Column('check_name', sa.TEXT(), nullable=True),
    sa.Column('reason_rule', sa.TEXT(), nullable=True),
    sa.Column('last_checked', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('responsible_role', sa.TEXT(), nullable=True),
    sa.Column('action_label', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_trial_id'), 'compliance_checks', ['trial_id'], unique=False)
    op.create_table('adverse_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('event_term', sa.VARCHAR(length=255), nullable=False),
    sa.Column('onset_date', sa.DATE(), nullable=True),
    sa.Column('resolution_date', sa.DATE(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('causality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_serious', sa.BOOLEAN(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverse_events_trial_id'), 'adverse_events', ['trial_id'], unique=False)
    op.create_index(op.f('ix_adverse_events_is_serious'), 'adverse_events', ['is_serious'], unique=False)
    op.create_index(op.f('ix_adverse_events_event_term'), 'adverse_events', ['event_term'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('responsible_role', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('action_label', sa.TEXT(), nullable=True),
    sa.Column('resolved_at', sa.TEXT(), nullable=True),
    sa.Column('resolved_by', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_trial_id'), 'alerts', ['trial_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_table('ayur_patients',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('area_city', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('assigned_trial_id', sa.TEXT(), nullable=False),
    sa.Column('treatment_site', sa.TEXT(), nullable=False),
    sa.Column('assigned_doctor_name', sa.TEXT(), nullable=False),
    sa.Column('treatment_status', sa.TEXT(), nullable=False),
    sa.Column('treatment_duration', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('contact_info', sa.TEXT(), nullable=True),
    sa.Column('accessibility_needs', sa.TEXT(), nullable=True),
    sa.Column('registration_date', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('ctms_timelines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.TEXT(), nullable=False),
    sa.Column('trial_title', sa.TEXT(), nullable=False),
    sa.Column('stage_protocol_status', sa.TEXT(), server_default=sa.text("'Completed'"), nullable=True),
    sa.Column('stage_protocol_date', sa.TEXT(), nullable=True),
    sa.Column('stage_iec_status', sa.TEXT(), server_default=sa.text("'Completed'"), nullable=True),
    sa.Column('stage_iec_date', sa.TEXT(), nullable=True),
    sa.Column('stage_ctri_status', sa.TEXT(), server_default=sa.text("'Completed'"), nullable=True),
    sa.Column('stage_ctri_date', sa.TEXT(), nullable=True),
    sa.Column('stage_activation_status', sa.TEXT(), server_default=sa.text("'Completed'"), nullable=True),
    sa.Column('stage_activation_date', sa.TEXT(), nullable=True),
    sa.Column('stage_recruitment_status', sa.TEXT(), server_default=sa.text("'In Progress'"), nullable=True),
    sa.Column('stage_recruitment_date', sa.TEXT(), nullable=True),
    sa.Column('stage_monitoring_status', sa.TEXT(), server_default=sa.text("'In Progress'"), nullable=True),
    sa.Column('stage_monitoring_date', sa.TEXT(), nullable=True),
    sa.Column('stage_followup_status', sa.TEXT(), server_default=sa.text("'Upcoming'"), nullable=True),
    sa.Column('stage_followup_date', sa.TEXT(), nullable=True),
    sa.Column('stage_dblock_status', sa.TEXT(), server_default=sa.text("'Upcoming'"), nullable=True),
    sa.Column('stage_dblock_date', sa.TEXT(), nullable=True),
    sa.Column('stage_closeout_status', sa.TEXT(), server_default=sa.text("'Upcoming'"), nullable=True),
    sa.Column('stage_closeout_date', sa.TEXT(), nullable=True),
    sa.Column('overall_status', sa.TEXT(), server_default=sa.text("'In Progress'"), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigators',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), nullable=True),
    sa.Column('affiliation', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_aiia', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigators_name'), 'investigators', ['name'], unique=False)
    op.create_index(op.f('ix_investigators_is_aiia'), 'investigators', ['is_aiia'], unique=False)
    op.create_index(op.f('ix_investigators_affiliation'), 'investigators', ['affiliation'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('permissions_json', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('role_name', sa.TEXT(), nullable=False),
    sa.Column('institution', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eligibility',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('age_from', sa.VARCHAR(length=50), nullable=True),
    sa.Column('age_to', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), nullable=True),
    sa.Column('inclusion_details', sa.TEXT(), nullable=True),
    sa.Column('exclusion_details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_trial_id'), 'eligibility', ['trial_id'], unique=1)
    op.create_table('protocol_deviations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('deviation_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('date_identified', sa.DATE(), nullable=True),
    sa.Column('reported_by', sa.VARCHAR(length=150), nullable=True),
    sa.Column('resolution_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_deviations_trial_id'), 'protocol_deviations', ['trial_id'], unique=False)
    op.create_table('ayur_patient_treatments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.TEXT(), nullable=False),
    sa.Column('stage_key', sa.TEXT(), nullable=False),
    sa.Column('stage_title', sa.TEXT(), nullable=False),
    sa.Column('stage_order', sa.INTEGER(), nullable=False),
    sa.Column('date_recorded', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('assigned_doctor_name', sa.TEXT(), nullable=False),
    sa.Column('dosage_frequency', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['ayur_patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pv_reporting_deadlines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trial_id', sa.INTEGER(), nullable=True),
    sa.Column('ctri_number', sa.TEXT(), nullable=True),
    sa.Column('trial_title', sa.TEXT(), nullable=True),
    sa.Column('report_type', sa.TEXT(), nullable=True),
    sa.Column('deadline_date', sa.TEXT(), nullable=True),
    sa.Column('submission_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('responsible_role', sa.TEXT(), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ayur_approvals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('approval_id', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('hospital_name', sa.TEXT(), nullable=False),
    sa.Column('approval_type', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('submission_date', sa.TEXT(), nullable=False),
    sa.Column('decision_date', sa.TEXT(), nullable=True),
    sa.Column('reviewer_notes', sa.TEXT(), nullable=True),
    sa.Column('action_required', sa.TEXT(), nullable=True),
    sa.Column('signature_id', sa.TEXT(), nullable=True),
    sa.Column('signature_hash', sa.TEXT(), nullable=True),
    sa.Column('signed_by', sa.TEXT(), nullable=True),
    sa.Column('signed_at', sa.TEXT(), nullable=True),
    sa.Column('signing_intent', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('role_name', sa.TEXT(), nullable=False),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('ctms_monitoring_visits',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('visit_code', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.TEXT(), nullable=False),
    sa.Column('trial_title', sa.TEXT(), nullable=False),
    sa.Column('site_name', sa.TEXT(), nullable=False),
    sa.Column('monitor_name', sa.TEXT(), nullable=False),
    sa.Column('visit_type', sa.TEXT(), server_default=sa.text("'Interim Monitoring Visit (IMV)'"), nullable=True),
    sa.Column('planned_date', sa.TEXT(), nullable=False),
    sa.Column('actual_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('visit_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('visit_number', sa.INTEGER(), nullable=False),
    sa.Column('window_days', sa.INTEGER(), nullable=True),
    sa.Column('required_assessments', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_trial_id'), 'visits', ['trial_id'], unique=False)
    op.create_table('ayur_trials',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trial_id', sa.TEXT(), nullable=False),
    sa.Column('trial_name', sa.TEXT(), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('intervention', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('hospital_name', sa.TEXT(), nullable=False),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('pi_name', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.TEXT(), nullable=False),
    sa.Column('end_date', sa.TEXT(), nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=False),
    sa.Column('target_participants', sa.INTEGER(), nullable=False),
    sa.Column('enrolled_participants', sa.INTEGER(), nullable=False),
    sa.Column('recruitment_status', sa.TEXT(), nullable=False),
    sa.Column('trial_status', sa.TEXT(), nullable=False),
    sa.Column('eligibility_criteria', sa.TEXT(), nullable=True),
    sa.Column('exclusion_criteria', sa.TEXT(), nullable=True),
    sa.Column('ethics_approval_status', sa.TEXT(), server_default=sa.text("'Approved'"), nullable=False),
    sa.Column('ctri_registration_status', sa.TEXT(), server_default=sa.text("'Registered'"), nullable=False),
    sa.Column('regulatory_status', sa.TEXT(), server_default=sa.text("'Approved'"), nullable=False),
    sa.Column('progress_pct', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('outcome_metric_name', sa.TEXT(), nullable=True),
    sa.Column('outcome_metric_value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id')
    )
    op.create_table('ctms_milestones',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('milestone_code', sa.TEXT(), nullable=False),
    sa.Column('trial_id', sa.INTEGER(), nullable=False),
    sa.Column('ctri_number', sa.TEXT(), nullable=False),
    sa.Column('trial_title', sa.TEXT(), nullable=False),
    sa.Column('milestone_name', sa.TEXT(), nullable=False),
    sa.Column('due_date', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('responsible_role', sa.TEXT(), nullable=False),
    sa.Column('is_overdue', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_synthetic', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_esignatures_orm_signature_id'), table_name='esignatures_orm')
    op.drop_index(op.f('ix_esignatures_orm_record_type'), table_name='esignatures_orm')
    op.drop_index(op.f('ix_esignatures_orm_record_id'), table_name='esignatures_orm')
    op.drop_index(op.f('ix_esignatures_orm_id'), table_name='esignatures_orm')
    op.drop_table('esignatures_orm')
    op.drop_index(op.f('ix_ayur_trials_orm_trial_id'), table_name='ayur_trials_orm')
    op.drop_index(op.f('ix_ayur_trials_orm_id'), table_name='ayur_trials_orm')
    op.drop_index(op.f('ix_ayur_trials_orm_condition'), table_name='ayur_trials_orm')
    op.drop_table('ayur_trials_orm')
    op.drop_index(op.f('ix_ayur_approvals_orm_trial_id'), table_name='ayur_approvals_orm')
    op.drop_index(op.f('ix_ayur_approvals_orm_id'), table_name='ayur_approvals_orm')
    op.drop_index(op.f('ix_ayur_approvals_orm_approval_id'), table_name='ayur_approvals_orm')
    op.drop_table('ayur_approvals_orm')
    op.drop_index(op.f('ix_ayur_adverse_events_orm_trial_id'), table_name='ayur_adverse_events_orm')
    op.drop_index(op.f('ix_ayur_adverse_events_orm_patient_id'), table_name='ayur_adverse_events_orm')
    op.drop_index(op.f('ix_ayur_adverse_events_orm_id'), table_name='ayur_adverse_events_orm')
    op.drop_index(op.f('ix_ayur_adverse_events_orm_event_id'), table_name='ayur_adverse_events_orm')
    op.drop_table('ayur_adverse_events_orm')
    # ### end Alembic commands ###
